name: Build and Package Installers

on: [push]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: |
          # Download files using curl or wget
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-model-installer
          push: false
          tags: lunamidori5/linux_model_installer
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile-localai-installer
          push: false
          tags: lunamidori5/linux_localai_installer
      - uses: docker/run-action@v2
        with:
          image: lunamidori5/linux_model_installer
          # ... commands to execute within the container
      - uses: docker/run-action@v2
        with:
          image: lunamidori5/linux_localai_installer
          # ... commands to execute within the container
      - uses: docker/stop-container-action@v1
      - uses: docker/prune-images-action@v1
