name: Check Python Code

on: [push, pull_request]

jobs:
  check-linux:
    runs-on: self-hosted
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install docker to system
      run: |
        apt-get install -y docker
    - name: Install dependencies
      run: |
        conda install flake8
        pip install docker python-on-whales pyyaml PyInstaller requests py-cpuinfo
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=25 --max-line-length=400 --statistics
    - name: Lint Markdown
      # You may pin to the exact commit or the version.
      # uses: tomwhross/write-good-action@5897a4ff597390bd521c5c3a6c062bf96147a341
      uses: tomwhross/write-good-action@v1.6
      with:
        # Name of Directory to scan with write-good [default is "."]
        directory: .
